### ISSUE TITLE
New Search UI for Pages, ModelAdmin and GridField

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-cms#1777]
# Overview

Update the way in which search functionality can be accessed throughout the CMS. This might need to be separated out into different issues/tasks if it functions differently for each area.

# Acceptance Criteria

## Baseline

 * I can trigger search easily regardless which section I'm in
 * The new search UI applies to ModelAdmin, Pages and any GridField implementations
 * I can bookmark search results wherever there's one "main" GridField

## Simple Search

 * I get useful results on a standard search field, without choosing which field to narrow down to
 * If multiple searchable lists appear on the same view (in the same tab or different tabs), it is clear which search filters are applied to which results
 * I can tell what records I'm going to be searching for (e.g. "Search MyObject")
 * I can clear my search term input (which also clears search results)

## Advanced Search

 * I can toggle a view with more advanced search inputs
 * I can search more fields than are presented in the result columns (if configured by dev)
 * I can easily use sophisticated search filters with a dozen or more fields of different types
 * I can clear search results

## GridField-specific

 * I am able to clear the search term and reset the search results, which shows the default GridField items again
 * A view can have multiple searchable GridFields, and search controls are clearly associated with the related GridField

# Notes

 * Designs flow: https://invis.io/FTG16IYV5KB#/299750159_POC_CMS_Search_Menu_C3 (Model/gridfield flow contains main comments)
 * Design guide: https://invis.io/YGGYS6HDMRK#/310647254_Search
 * Related: [General purpose search form component](https://github.com/silverstripe/silverstripe-cms/issues/2184)
 * Related: [New Search UI for AssetAdmin](https://github.com/silverstripe/silverstripe-cms/issues/2185)
 * Excludes the results of each section are presented (would be good to raise as separate issue based on individual sections)
 * Ensure all interactive elements have text alternatives (e.g. down arrow)
 * Replaces existing GridField column-based search implementation (`GridFieldFilterHeader`) in default configuration, but retain `GridFieldFilterHeader` for backwards compat. TBC if this applies to the PHP API only, or if we retain the ability to search per column 
 * We'll need to define what constitutes a "default search" (e.g. name and title column), needs to be configurable
 * Excludes creating "date range" fields (for now, should be separate before/after fields)
 * Should be implemented as one unified React component
 * Track under ORB-175

Older style of pages sections:
![image](https://cloud.githubusercontent.com/assets/555033/24597672/424fd81c-189b-11e7-91ad-b9e1e743cd32.png)

# Related

 * [#1891  Show advanced search filter tags in search overview](https://github.com/silverstripe/silverstripe-cms/issues/1891)
 * [Search for archived records](https://github.com/silverstripe/silverstripe-versioned/issues/38)

# Subtasks

- [x] Integrate into Pages admin
- [x] Fix Page Results 'back' functionality
- [x] Integrate into Model admin
- [x] Integrate into GridField
- [x] Update tests
- [x] UX Review

# PRs
- [x] https://github.com/silverstripe/silverstripe-admin/pull/594
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2224
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8338
- [x] https://github.com/silverstripe/silverstripe-versioned-admin/pull/57
- [x] ~~https://github.com/silverstripe/silverstripe-framework/pull/8309~~

**Comment by chillu** [comment]
Note that I'm proposing to remove the ability to show page results in a tree view: https://github.com/silverstripe/silverstripe-cms/issues/1926

**Comment by newleeland** [comment]
**Potential ModelAdmin design direction** [Dev feedback required]

![artboard copy](https://user-images.githubusercontent.com/8085295/32524216-8b8db4ec-c483-11e7-8f48-a213e0a465cc.png)
Move search all the way to the right

![artboard](https://user-images.githubusercontent.com/8085295/32524254-aeb0421e-c483-11e7-9a2d-f07577a49493.png)
Search field takes precedence, and covers Tabs and even title when search. 

![artboard copy 2](https://user-images.githubusercontent.com/8085295/32524263-b861a870-c483-11e7-9b1b-c18c484b05fe.png)
Advance options fields will be dependent on the content of that section.

**Comment by newleeland** [comment]
## Search mechanics changes 
Another issue is the search mechanics vary between Page/Files and ModelAdmin/gridfields. The newer search has only one default field to search, this is good design (nngroup). This works well for areas like Pages/Files which have one primary search term – the **NAME**. Modeladmins/Gridfields 
don't have a primary search term to default too. 
### **Solution**
Hence, if we were to use the single input search in ModelAdmin/gridfields, it would be required to search across all columns.

## Search hierarchy changes
Further research suggests that this search would not work for rest of CMS (with modelAdmins, grid fields) as modelAdmin search is currently right next to the tabs on the top bar (top level). This suggests everything across the tabs are search, however, this is not the case. The search only searches within the tab that is selected. 
![screenshot-2017-11-16 silverstripe - test modeladmin](https://user-images.githubusercontent.com/8085295/32862597-7ae58e90-cabd-11e7-8ebc-4174dfb04b0f.png)
### **Solution** 
So there are 2 two alternative positions 
**1. Underneath the tabs instead of next to the tabs**
Positionally this works rather well, however, the visually it looks out of place for modeladmins wouldn't align with Files/Pages
![poc_pl_gridfield_search filters copy 3](https://user-images.githubusercontent.com/8085295/32866938-1634f82a-cacf-11e7-9fc0-1b0ef10b8d81.png)
![poc_pl_gridfield_search filters copy 4](https://user-images.githubusercontent.com/8085295/32866945-1ec87106-cacf-11e7-8267-e495a631848a.png)
![poc_pl_gridfield_search filters copy 5](https://user-images.githubusercontent.com/8085295/32866996-50d952e6-cacf-11e7-9d7a-b9a7c788cf66.png)


**2. inline with gridfield labels on the right side. (his direction has major UX issues)**
like search field needs to collapse after searching, in case the user needs to use the sort functionality. This means user needs click again search to research.
![poc_pl_gridfield_search filters copy 9](https://user-images.githubusercontent.com/8085295/32866597-64c5cc32-cacd-11e7-82d9-1226515ecf44.png)
![poc_pl_gridfield_search filters copy 6](https://user-images.githubusercontent.com/8085295/32866607-6acf300a-cacd-11e7-8e37-c1d372316a8a.png)
![poc_pl_gridfield_search filters copy 7](https://user-images.githubusercontent.com/8085295/32866614-71b796fa-cacd-11e7-93bc-3fdd0c10da93.png)
 
## Combined solution
![poc_pl_gridfield_search filters copy](https://user-images.githubusercontent.com/8085295/32867234-dcba22b2-cad0-11e7-861f-5a0e2123d05d.png)
![poc_pl_gridfield_search filters](https://user-images.githubusercontent.com/8085295/32867250-ecad9f5a-cad0-11e7-8a22-b9a372ba201a.png)
![poc_pl_gridfield_search filters copy 2](https://user-images.githubusercontent.com/8085295/32867282-1e6ad5da-cad1-11e7-8a39-7af959e86c24.png)
![poc_pl_gridfield_search filters copy 8](https://user-images.githubusercontent.com/8085295/32867290-24aa2ebe-cad1-11e7-91c5-4090aa33bd50.png)

**Comment by chillu** [comment]
I think it's time for some acceptance criteria :D

 * I can trigger search easily regardless which section I'm in (consistent placement)
 * I get useful results on a standard search field, without choosing which field to narrow down to
 * I can search more fields than are presented in the results
 * I can easily use sophisticated search filters with a dozen or more fields of different types
 * It's easy to tell when search filters are applied, without obscuring the results too much
 * If multiple searchable lists appear on the same view (in the same tab or different tabs), it is clear which search filters are applied to which results
 * I can clear search results

**Comment by clarkepaul** [comment]
This issue has become ModelAdmin search or general purpose search—its supposed to be site tree search which becomes a list view search, so no tabs etc. as per designs provided here https://github.com/silverstripe/silverstripe-cms/issues/1891

@chillu do you want this to become a general purpose search issue? maybe we adjust the issue heading.

**Comment by newleeland** [comment]
![poc_pl_gridfield_search filters copy](https://user-images.githubusercontent.com/8085295/33191428-02e07a9c-d11e-11e7-9055-822ef64edf20.png)
![slice](https://user-images.githubusercontent.com/8085295/33191429-030d43a6-d11e-11e7-8b22-292a503dba53.png)

**Comment by chillu** [comment]
@newleeland I like it :) My concern is that we're hiding away the "more search options" panel with a miniature triangle icon without a label. That's following on from the "assets" UI, but kind of assumes that most of the time you'd search with the single field instead of opening "advanced" options. That's a technical challenge, since not all database columns are configured to be "searchable" (don't have a full text index). Which might be a separate technical task to allow for a design like this to work by default. The triangle is right in the middle between "clear" and "close" icons, so it's going to be hard to aim for on mobile screens. Also what's the difference between "clear" and "close"?

You're also introducing a presumably editable search syntax here: Are authors expected to type out `Type:Page Locations` here, limiting to `Page` type, and doing a full text search on `Locations`? That implies that we can convert these text representations back and forth between form fields and the editable summary. Or would `Type:Page` be readonly, and only `Locations` editable?

In general, please add more reasoning for your designs on tickets, where you're introducing major new concepts like a custom search syntax.

**Comment by clarkepaul** [comment]
I should also add some of the discussions I've had with @newleeland.
* Firstly design progressions (when it's not final) should happen in Invision so we don't bloat the issues and use comment there.
* "Clear" would be removed unless we can ensure it doesn't get users mixed up with the X, "clear" seems like the least valuable thing and I'd prefer an "advanced" or "options" label with the dropdown. 
* When a search is made without using the main search field (only using advanced), we need to show what has been searched either in the field or in a notification. If placed in the field we could give it a read-only feel but would be great if it could be used to search also (not a deal breaker), but it looks really having done a search without the search field showing what has been searched.
* With extremely wide screens we could limit the width of the search field and right align (eg. over 1200px or 1400px?).

**Comment by newleeland** [comment]
**Updated POC design**
https://invis.io/NP79NDU4J#/267837241_POC_PL_Gridfield_Search_1

**Comment by newleeland** [comment]
##Updated Designs
**Basic Search mechanic (ModelAdmin)** WIP designs https://invis.io/FTG16IYV5KB#/284539432_POC_CMS_Search_Model_Start_C2
- I have similar search interactions throughout CMS
- I have a Search bar appear only when I require it.
- I have more options for narrowing down my search 
- I am presented with the ability to clear search field of searchbar when values are inserted
- I have the ability clear the advance search

###Variation
**Pages (collapsed tree variant)** 
https://invis.io/FTG16IYV5KB#/284543655_POC_CMS_Search_Page_Start_C2

**Files advance search**
https://invis.io/FTG16IYV5KB#/284543652_POC_CMS_Search_Files_Advance_C2

##Note
- Advanced search will vary between pages/files/models
- Develop in consideration to new search results designs #1891 

**See list of all Search flows** 
https://invis.io/FTG16IYV5KB#/284539428_POC_CMS_Search_Menu_C2

**Comment by chillu** [comment]
> I have been communicated the scope of the search before searching (eg Search pages)

Renamed to "I can tell what I'm going to be searching for (e.g. "Search MyObject")"

> I have a Search bar appear only when I require it, and can open/close the search bar when required

Renamed to "I can toggle a view with more advanced search inputs"

> If multiple GridFields are in the same view I have the possibility to search these individual GridFields independent of the other GridFields

Simplified to "A view can have multiple searchable GridFields, and search controls are clearly associated with the related GridField"

**Comment by chillu** [comment]
@newleeland Your ModelAdmin designs don't account for tabs. You pointed that out as an issue back in November. I assume that means we're keeping the search icon left of the tabs, as currently implemented?

**Comment by clarkepaul** [comment]
I think that the search icon is positioned in the top toolbar if there are no tabs (as per Pages and Files), and this was done to allow people to build ModelAdmins with a search functionality over an entire admin area if they have a single type of "thing" which could have a nested structure (@chillu not sure if this is actually needed though?), but if the search is only based on GridField data then it would be below the North Toolbar as per the GridField designs.

**Comment by clarkepaul** [comment]
> There is always toplevel tabs in ModelAdmin, even if you only manage a single model. It's technically not possible to search across multiple managed models through the same search UI or trigger.

Thats what I'm trying to say, Pages and Files differs from most areas because you can search an entire hierarchy, I just wasn't sure about whether people could build a ModelAdmin with the same search modal as I'd never seen it before—your reply has clarified that point that you can't.

This differs from GridFields where you can only search a single level, so the search icon makes sense to be more attached to that area, especially if there are multiple Gridfields on a single view 

And we're moving the Modal admin search icon from before the tabs to sit within the tab you need to search within as you can't search across multiple tabs.

**Comment by chillu** [comment]
Design notes for @newleeland:
- Search in gridfield can't overlap actions - you need persistent search and actions at the same time
- TBD: Which actions make sense when you search, should we limit them?
- ModelAdmin shouldn't show search next to tabs, need to be within GridField within a specific tab
- ModelAdmin designs are confusing in terms of their titles, refer to actual implementations below
- Needs to be clear when you look at ModelAdmin *overview* (one GridField only) vs. *detail view* (zero or more GridFields, mixed with other fields)
- Check how to "clear search input" vs. "close search field" vs "close advanced search"

![image](https://user-images.githubusercontent.com/111025/40591709-235c0fe2-626a-11e8-8521-91319e6b3982.png)
![image](https://user-images.githubusercontent.com/111025/40591716-330cfffa-626a-11e8-813e-2297a799554a.png)
