### ISSUE TITLE
Review Consistency of Popovers in Pattern Library

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-cms#2155]
### Tasks
**Analyse and Update**
- [x] Specify dimensions and variables used (reference CSS variables used)
- [x] Variations: Account for variations/modifiers btn-primary, btn-success, toolbar--north, toolbar--south
- [x] Content: Whats allowed within a components (eg. other components)
- [x] Location: Where can component can be used (eg breadcrumb only in toolbar?)
- [x] Responsiveness
- [x] Interactions: specified (fade, movement... )
- [x] Accessibility considerations (check colours, focus states etc.)

**Update Pattern Library Documentation**
- [x] Designs uploaded to DSM
- [x] Designs uploaded to InVision components
- [x] Link added from DSM to InVision component
- [x] Create issue for each component with a list of changes that we want made

**Recommend CSS changes**
- [x] For each component create a checklist of unknown CSS which should be confirmed its needed (what can we remove, they should naturally inherit styles from base components eg. hover, active colours)
- [x] Components should have styles inherited from base component or base styles. Can we need to remove overriding styles? (go over with Luke)

**Checks**
- [x] Pattern library UX/design has been checked by designer

### Related issue
https://github.com/silverstripe/silverstripe-asset-admin/issues/779
