### ISSUE TITLE
General purpose search form component

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-cms#2184]
Parent story: https://github.com/silverstripe/silverstripe-cms/issues/1777

# Acceptance Criteria

 * I can type in a search term
 * There's a configurable placeholder
 * I can clear my search term input (both in collapsed and expanded view)
 * I can toggle a view with more advanced search inputs
 * The advanced search inputs are configurable via a form schema
 * There are event hooks for triggering a search and clearing search results

# Notes

 * Designs: https://invis.io/FTG16IYV5KB#/299750159_POC_CMS_Search_Menu_C3
 * Excludes [search filter tags](https://github.com/silverstripe/silverstripe-cms/issues/1891)
 * To be added to pattern library
 * Related: [New Search UI for AssetAdmin](https://github.com/silverstripe/silverstripe-cms/issues/2185)
 * Related: [New Search UI for Pages](https://github.com/silverstripe/silverstripe-cms/issues/1777)

# Tasks

* [x] Set up component
* [x] Define reducer, state, actions
* [x] Update usage doc
* [x] Update Pattern lib
* [x] Write unit test
* [x] Update AssetAdmin to use the new search component instead (technically not part of the card, but it gives me something to test the component against and it won't be very long).

# Pull requests
* [x] https://github.com/silverstripe/silverstripe-admin/pull/572
* [x] https://github.com/silverstripe/webpack-config/pull/23

# Related PRs
* https://github.com/silverstripe/silverstripe-asset-admin/pull/812 You can use this one to see the new Search component in action.

**Comment by maxime-rainville** [comment]
The asset admin search components looks like this right now:
```jsx
<Search
    onSearch={this.handleDoSearch}
    id="AssetSearchForm"
    searchFormSchemaUrl={searchFormSchemaUrl}
    filters={filters}
    formData={{}}
    />
```
`filters` receives GET URL param. 
`formData` is populated from the redux state.
`searchFormSchemaUrl` is mandatory and allows a form schema to be passed.
AssetAdmin give it a `folderId` props which it doesn't do anything with.

I would tweak things this way.
```jsx
<Search
    onSearch={this.handleDoSearch}
    onClear={this.clear}
    onShowFilters={this.showFilter}
    onHideFilters={this.showFilter}
    onShow={this.showSearch}
    onHide={this.hideSearch}

    show={true}
    showFilters={true}
    toggable={true}
    placeholder={searchTerm}
    id="RandomSearchForm"
    formSchemaUrl={searchFormSchemaUrl}
    filters={filters}
    formData={{}}
    />
```

`placeholder` is optional and will default to `Search ...`
`toggable` is true and `show` is false, an search button will be displayed without a search box.
`toggable` is true and `show` is true, an search box will be displayed with an X allowing the user the hide the search box.

`formSchemaUrl` will be optional. If not set no advance filters will be available.

**Comment by maxime-rainville** [comment]
I'm almost done with the basic set up of the component and the styling. There's a few question to clear up:
* The current File Search component has an _Advanced_ label when you hover over the drop down icon. That would clash with the clear/enter label, so I presume we need ditch this label.
* There's a _clear_ label that appears in some of the mock up, where the 
![image](https://user-images.githubusercontent.com/1168676/42430534-0aae6cb0-8394-11e8-9ae1-daa8577a720e.png) sometimes appear. It's not immediately apparent to me when I should display _enter_ and when I should display _clear_.

**Comment by maxime-rainville** [comment]
Yeah finally got it over line. 

Here's what it looks like. https://youtu.be/xNFkyLOgrzg

**Comment by robbieaverill** [comment]
Looks awesome! Does the content area need a loading indicator to prevent the search button from rendering half way off the container? 😛

**Comment by maxime-rainville** [comment]
I've made some adjustments based on @clarkepaul's feedback: https://youtu.be/eAyTQYW-kXM

* The bottom shadow will now display over the file side panel.
* The Advanced fitler collapsable will now line up with the drop down button.
* There's now a clear button showed directly in the search box where the [enter] would be shown as per the mock ups.

Getting the switch between the [enter] hint and clear button ended up being a bit of a mission, because I had to track if the search form was dirty and make sure it got reset to pristine on search.

The `enter` hint will show if the search box has the focus and is dirty.

The clear button will show if there's data to clear and if the _enter_ hint is not showing.

**Comment by chillu** [comment]
Looks great, those Youtube previews are super helpful for low friction review. Great to see the pattern library being actively used as well

**Comment by clarkepaul** [comment]
Functionality is working great :), do we have control over how the search suggested results appears?

**Comment by maxime-rainville** [comment]
The _suggested_ results you see in the vid is just the browser's native auto-suggest features. It remembers values you posted in the form previously and will offer them to you again.

We could use `autocomplete=off` on the input field and provide our own auto suggest feature, but that would probably need to be another card.

**Comment by maxime-rainville** [comment]
@lukereative and I had a catch up with @newleeland today. That should be be last changes to this guy ... fingers crossed. Here's what's been changed

* Got rid of the blue glow and blue border on focus.
* Only display the shadow when the Search input box has the focus or when the advanced filters are open.
* The clear button in the search box will now focus on the search box after click.
* The clear button in the advanced filters form will now focus on the first field after click.

https://youtu.be/YEhsHme3pyk
