### ISSUE TITLE
Include version number in generator meta tag

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-cms#2708]
# Description

We already provided a generator meta tag that tells the world that a site is running Silverstripe CMS. Adding a version number would allow us to better track adoption and upgrades in the real world

# Acceptance criteria
- [ ] [`SiteTree::MetaComponent`](https://github.com/silverstripe/silverstripe-cms/blob/c75448669300ce5ed94a6e20c0a386ff4219167d/code/Model/SiteTree.php#L1395) is updated to include the version number
- [ ] The version number is determined using a mechanism similar to [LeftAndMain's `VersionProvider`](https://github.com/silverstripe/silverstripe-admin/blob/d3fc48cde0aef36518d0b7efd11dd5711bef6be4/code/LeftAndMain.php#L161)
- [ ] The version number is provided by default
- [ ] Format is switch to "Silverstripe CMS 4.xx" without the patch release number
- [ ] It's possible to easily disable the generator meta tag
- [ ] There's clear guidance on how to disable this feature for project who consider this information sensitive.
- [ ] Validate performance and implement caching if necessary

# Related issue
- https://github.com/silverstripe/silverstripe-admin/issues/1256

# PRs
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10235
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2721

**Comment by lerni** [comment]
I understand the desire to better track version adoption but I consider adding version as a security risk. I know you can remove the tag but, but as default it'll remain for the majority of projects and makes vulnerability analysis much to easy.

**Comment by michalkleiner** [comment]
I agree with lerni. In theory, exposing any version information on a fully patched and properly set up system is no risk, again, in theory, but the real world is different.

If we added this as an optional feature behind a config flag, off by default, I'd be happy to have it, and leave it up the site owners/site vendors to decide whether they want to turn it on.

**Comment by maxime-rainville** [comment]
There's already plenty of ways to identify that a site is running Silverstripe CMS. Not disclosing that a site is running version X is just an extension of the "security by obscurity" fallacy. It provides no meaningful security layer and prevents us from collecting useful metadata about Silverstripe CMS usage in the wild.

**Comment by emteknetnz** [comment]
Security by obscurity provides virtually zero additional security and it cannot be relied on whatsoever

For instance, a determined attacker could easily work out the version of silverstripe by looking at the md5 hash of `/_resources/vendor/silverstripe/admin/client/dist/js/bundle.js` which can be directly accessed by non-logged in users

**Comment by michalkleiner** [comment]
I don't think anyone here is saying not showing the version provides additional security. I do say though that it should configurable, whatever the default might be, so that folks running their sites can adjust it to their needs.

**Comment by emteknetnz** [comment]
I'm fine with configurable.  It needs to be on by default otherwise it will provide next to no value as pretty much no-one will turn this on

**Comment by maxime-rainville** [comment]
Yeah ... if we turn it off by default, we might as well not bother implementing this at all.

**Comment by kinglozzer** [comment]
I don’t think this is a good idea. Hiding version numbers doesn’t offer an individual site any additional security, but exposing this information across all installations (by default) makes it trivial for attackers to draw up a list of sites that are vulnerable to specific exploits.

Currently, there’s no way to discern whether a site is running the latest 4.9 release or a much older one besides actually attempting a known exploit. For some exploits the effort required is trivial so that won’t matter, but for other exploits we’d be making life much easier for would-be attackers.

It also doesn’t seem like a very reliable way to track this data. Many projects using Silverstripe are `noindex`-ed, and I know for a fact that penetration testers testing any of our sites will recommend we hide this info because we’ve had the same conversations with them about hiding webserver info.

**Comment by dhensby** [comment]
What is the objective here, "to better track adoption and upgrades in the real world"? Well, there are already means for that. There is (or used to be) stats gathering by the installer, we also have composer stats too, which we can no doubt access to ascertain adoption rates.

How does the meta tag actually fulfill this objective? Is there a SS Spider that goes around crawling all of the sites on the web and then gathering this meta tag? Is it an enhancement that would help something like BuiltWith to provide more helpful stats?

What I'm getting at is, does this solution actually help achieve the stated objective?

As @kinglozzer points out, version numbers are essentially a no-no when pen' testers or any security evaluation is done. Yes, it doesn't make your site any more secure, but it does create an easily enumerable way to identify vulnerable sites and for that list of sites to be collated and distributed.

I also accept @emteknetnz point that some other data can easily be fingerprinted to work out the version of an SS site too, so the explicit version isn't going to be a game changer for drawing up a list of vulnerable sites to an attacker that's focused on SS.

Therefore I'd suggest that the balanced approach is to put the version number in and allow it to be configurable (including turning off the generator tag completely). Though, of course, overriding the meta tags is already possible for anyone that does or doesn't want to have this data exposed.

**Comment by maxime-rainville** [comment]
Can we get a vote on this?

:+1: If you're OK with it
:-1: If you're not.

**Comment by michalkleiner** [comment]
👍  provided it can be turned off easily and it's clearly documented and mentioned in the changelog I'm ok with having it as a feature.

**Comment by sminnee** [comment]
Hola, long time no see everyone!

I've got mixed feelings about this. although "security by obscurity isn't a protection", making it easier to bulk-scan for vulnerable versions could potentially aid attackers casting about for a site that happens to be vulnerable. Especially since those who don't adjust the default setting will also be those who are more likely to have put their site up with no maintenance plan.

That said, it's common practise to list version numbers by default, just as it's common practice for security assessors to ask that this is turned off, so adding the feature isn't egregious.

**Comment by maxime-rainville** [comment]
On the bulk scanning point, it would be relatively trivial to compute the HASH of common JS files we shipped in admin and use that to figure out what version is being shipped. That's probably a point we should include in the doc attached to this for the benefit of people who are really concerned about exposing which version they are using.

**Comment by lerni** [comment]
HASH of bundles is really something to watch out but I also think this is "harder" to find, since it's less likely to be indexed?

https://publicwww.com/ lists 15331 sites with SilverStripe Generator tag. This illustrates how easy it'll become for potential attackers to find affected sites in case of an exploit. The surface becomes bigger, so it than really is a security issue and won’t be about obscurity. That’s why I still think, even if you can turn it of, exposing version is kind of a careless default.

**Comment by maxime-rainville** [comment]
All PR have been merged.
