### ISSUE TITLE
Page Search opens unexpanded tree view by default (should be list view)

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-cms#632]
created by: nicolaas
created at: 2013-01-01
original ticket: http://open.silverstripe.org/ticket/8163

---

when doing a search (filter) for a page type in the CMS (3.0.3), you find the relevant page, BUT the sitetree does not automatically open to the relevant page.

In some ways, I think it would be better if any searches open the gridfield view rather than the sitetree view. 

## AC

- List view is switched to when user searches for pages
- Display breadcrumb for search items
- Remove "Add page" action
- User has the ability to use the view toggle to navigate away from list view into tree view

### Excluded:

- Search field component as per files area to be implemented as separate issue
- Search notification updates which information about what has been searched to be implemented as separate issue

## Tasks

- [x] Switch to list view when in search view
- [x] Remove "Add page" in search view
- [x] Add breadrumbs

## Related

 * [Retain list view state](https://github.com/silverstripe/silverstripe-cms/issues/503)
 * [Page search should show filter criteria and highlight search filters](https://github.com/silverstripe/silverstripe-cms/issues/1891)

## Pull request

- [x] https://github.com/silverstripe/silverstripe-cms/pull/1902
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7196

**Comment by chillu** [comment]
Deep default result:
![image](https://user-images.githubusercontent.com/111025/27845445-a7ff324e-6183-11e7-8300-fbea61fea790.png)

After FIVE expansion clicks:
![image](https://user-images.githubusercontent.com/111025/27845453-b32329e6-6183-11e7-8abf-7e10ca456dbb.png)

List view:
![image](https://user-images.githubusercontent.com/111025/27845460-c0c61d1a-6183-11e7-9c33-4c405a378f69.png)

I think we should fix this for 4.0, it makes page search on non-trivial page trees unusable by default. @clarkepaul What do you think?

**Comment by clarkepaul** [comment]
Yeah if it doesn't overload the system, like if thousands of pages exist. Maybe if it was too many pages then we could alert the user and then allow them to view them in list view. Either way needs improving.

**Comment by chillu** [comment]
It's much cheaper to show page results in a list view than in the tree view (since it doesn't need to reconstruct the whole "parent" structure of a search result). My point is that I think the list view is a better default, both when search is triggered in page editing context, and when you're on the `admin/pages` overview. I don't see a need for search results to show in the sidebar next to your page edit form when you trigger the search. If you navigate into a search result, that's useful. But not when you trigger the search. Does that make sense?

**Comment by clarkepaul** [comment]
Yup it does, for consistency across sections as well (in files it is also a flat list for results and not nesting—although presented as grid), need to match ways out (back to where you where, or back to all pages/files) if you clear the results.

**Comment by chillu** [comment]
- Leave tree view as-is (no expansion)
- Switch order of tabs around (list first), that might already fix the loading preference
- No changes to search form behaviour (discussed elsewhere)
- When search form is used in "page edit" mode, send to same view

**Comment by clarkepaul** [comment]
@chillu we think there would be the need to show a page/file(s) location to some degree in search results. Is it possible as part of this issue to add an additional column for either:
 * Parent page
 * Full path to page

This should provide more context to the searched item and help clarify results that share the same name. My understanding is that creating a full path would be too demanding on the system but providing a link to the items parent would be doable, just want to confirm this?

By introducing the list view we would loose the ability to compare each searched item  with its preview but I think that is a trade off we need to make.

Separate issue to improve results:
There is no indication or ability to refine searching just page names, just content or everything. They are mashed together which can result in a lot of returned results on larger sites. eg. if you search "about" nearly every page in a site would be returned when you might only want to search for pages with "about" in the page name.

**Comment by chillu** [comment]
I think implementing breadcrumbs in the list view would be feasible, there's already a method for it. It'll cause a bit more processing, but with ~15 results that's acceptable. I'll leave it to the implementor here if that's doable as part of the card, or if it's split out to another card.

**Comment by clarkepaul** [comment]
Designs for peer review by a dev would be good of the following https://invis.io/ZACM32DPC#/244049029_Pages_Search_Results_1_Tree

Includes:
 * Full path to pages

To be removed: 
 * Actions for "Add page" and other actions
 * View toggle

Excluded:
 * Search field component as per files area (to be implemented as separate issue)
 * Search notification updates which information about what has been searched (to be implemented as separate issue)
